### ISSUE TITLE
Triart: Optimize iterations 2 takes exponentially as long as optimize iterations 1

### ISSUE THREAD

**Issue by DaaOtt** [ruarai/Trigrad#1]
I'm using a dark, 1920x1080 concert photo with some pretty lights. On the default sample level, Optimize iterations 1 took 10 seconds, but optimize iterations 2 takes multiple hours, using around 40-50% CPU.

**Comment by ruarai** [comment]
This is something I definitely need to make clearer in the UI.

The bottom setting on the slider is zero iterations, meaning there is no work done by the optimiser. Above that, then yes, the computation time will increase massively.

The optimisation is optional and not something every image will need to have applied to it, but it can improve image quality massively.

The time is takes does sound excessively high, especially if that is just one iteration. How many samples/_re_samples are you doing?

Sorry for the confusion.

PS: I probably should make a triart repo.
